spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sbms
    username: root
    password: Root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
server:
  port: 8098

